var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/portfolio/mean-reversion-ou/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2b004a37._.js")
R.c("server/chunks/ssr/_d25179f9._.js")
R.c("server/chunks/ssr/_da150cae._.js")
R.c("server/chunks/ssr/[root-of-the-server]__36f71767._.js")
R.c("server/chunks/ssr/node_modules_next_dist_8df46922._.js")
R.c("server/chunks/ssr/node_modules_0ecec565._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/app_global-error_tsx_9170b7a0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d0cfa24e._.js")
R.c("server/chunks/ssr/app_error_tsx_5275429f._.js")
R.c("server/chunks/ssr/app_loading_tsx_b05711b0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_portfolio_mean-reversion-ou_page_actions_0b46a4bf.js")
R.m(66832)
module.exports=R.m(66832).exports
